### ISSUE TITLE
Feature: visualize bus/train positioning on map

### ISSUE THREAD

**Issue by JasonBarahan** [JasonBarahan/TrackMyTransit#2]
**Tasks**
- [x] Find a map API/package compatible with Java Swing
- [x] Create appropriate files in line with Clean Architecture
- [x] Handle point generation (input data requires vehicle id, route, lat, long), output data is a view
- [x] Handle cases where vehicles cannot be plotted for whatever reason (invalid coordinates, etc...)
- [x] Create unit tests (#39)

**Key notes**
- The API returns longitude/latitude, we could port this to a map which Java Swing supports, and allow for vehicle locations to be placed visually.
- Use arrows/some other indicator to denote direction of travel (e.g.: eastbound/westbound)
- Upon opening, the map should be centered at the vehicle's specific location. The current station a user is searching from could also be included in the map view upon opening,
- The vehicle's specific location could be accompanied by additional information, such as last stop serviced, next scheduled stop, service updates and disruptions (future feature for consideration)

**Caveats**
- Displaying text next to map points representing vehicle location may be troublesome

**Comment by JasonBarahan** [comment]
This feature is relevant to user story 3 from the revised blueprint

**Comment by JasonBarahan** [comment]
Reference

![image](https://github.com/JasonBarahan/TrackMyTransit/assets/122300705/4112d20c-05ca-4f46-a1c9-91566162e2f8)

**Comment by JasonBarahan** [comment]
Implemented in PR #57 which was subsequently merged. Marked as completed.
