### ISSUE TITLE
Feature: Populating vehicle names that depart the earliest from a train station/bus stop

### ISSUE THREAD

**Issue by jacqnnn** [JasonBarahan/TrackMyTransit#44]
**Task**
- [X] Retrieve a list (at most 3) of trains' names from Api call and display them in `show_incoming_vehicles` panel.

> - [x] Change trains into all vehicles (trains and buses) in the first task.

*_Note: After discussing with team,  due to time constraint, we decided to move this task to be a future feature [#47]_

- [X] handle error cases where api call fails (no content, bad request, internal server error, service unavailable, gateway timeout...)
- [X] Implement a single "Show Map" button at the bottom of the `show_incoming_vehicles` panel. [#50]
- [x] Write unit tests code (#43)

**Notes:**
1. When the api call returns less than or equal to 3 vehicles for a certain station, display all in `show_incoming_vehicles` panel, if greater than 3, filter out the 3 vehicles taht will depart the earliest and display in `show_incoming_vehicles` panel.
2. Error cases are handled with only _ONE_ popup window that says "Incoming Vehicles Retrieval Failed...". Errors are not specified.
